print("*****Students Detail*****")
name=input("Enter your Name: ")
collage=input("Enter your college Name: ")
rollno=int(input("Enter your Roll no:"))
studentno=int(input("Enter your student no: "))
add=input("Enter your adderess: ")
age=int(input("Enetr your age: "))

print("***** type *****")
print(type(name))
print(type(collage))
print(type(rollno))
print(type(studentno))
print(type(add))
print(type(age))

print("****Student" \
" Data ****")
print("name:",name)
print("collage:",collage)
print("roll no:",rollno)
print("student no:",studentno)
print("add:",add)
print("age:",age)